<script>
  import Header from '$lib/Header.svelte'
  import Footer from '../../lib/footer.svelte'
  import { addplan, getplans, login } from '$lib/db.js'
  let content = [
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Architectural Studies',
      cost: 'NZD $8,288.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; portfolio submission may be required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Arts',
      cost: 'NZD $7,185.60 - $8,288.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Anthropology', 'Criminology', 'Economics', 'English', 'History', 'Linguistics', 'Media, Film and Television', 'Philosophy', 'Politics and International Relations', 'Psychology', 'Sociology', 'Te Reo Māori', 'Theology'],
      prerequisites: 'NCEA Level 3 with University Entrance; specific subject requirements may apply depending on chosen major',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Commerce',
      cost: 'NZD $7,742.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Accounting', 'Commercial Law', 'Economics', 'Finance', 'Information Systems', 'International Business', 'Management', 'Marketing', 'Operations and Supply Chain Management'],
      prerequisites: 'NCEA Level 3 with University Entrance; Mathematics recommended',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Communication',
      cost: 'NZD $7,185.60 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Communication and Social Change', 'Communication and Technology', 'Communication in Leadership'],
      prerequisites: 'NCEA Level 3 with University Entrance',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Dance Studies',
      cost: 'NZD $7,185.60 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; audition may be required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Design',
      cost: 'NZD $8,288.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; portfolio submission may be required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Education (Teaching)',
      cost: 'NZD $7,185.60 per year for domestic students',
      location: 'Epsom Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in education or related subjects beneficial',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Education (Teaching English to Speakers of Other Languages)',
      cost: 'NZD $7,185.60 per year for domestic students',
      location: 'Epsom Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in languages or linguistics beneficial',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Engineering (Honours)',
      cost: 'NZD $9,583.20 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; strong performance in Mathematics with Calculus and Physics required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Fine Arts',
      cost: 'NZD $8,288.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; portfolio submission may be required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Global Studies',
      cost: 'NZD $7,185.60 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Global Environment and Sustainable Development', 'Global Politics and Human Rights', 'International Relations and Business', 'Transnational Cultures and Creative Practice'],
      prerequisites: 'NCEA Level 3 with University Entrance; background in social sciences recommended',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Health Sciences',
      cost: 'NZD $9,236.40 per year for domestic students',
      location: 'Grafton Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in sciences recommended',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Laws',
      cost: 'NZD $7,185.60 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; high academic achievement required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Music',
      cost: 'NZD $8,288.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Creative Practice: Classical', 'Creative Practice: Composition', 'Creative Practice: Jazz', 'Creative Practice: Popular Music', 'Music Studies'],
      prerequisites: 'NCEA Level 3 with University Entrance; audition may be required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Nursing',
      cost: 'NZD $9,236.40 per year for domestic students',
      location: 'Grafton Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in sciences recommended',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Optometry',
      cost: 'NZD $9,236.40 per year for domestic students',
      location: 'Grafton Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in sciences required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Pharmacy',
      cost: 'NZD $9,236.40 per year for domestic students',
      location: 'Grafton Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in sciences required',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Property',
      cost: 'NZD $7,742.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; Mathematics recommended',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Science',
      cost: 'NZD $7,185.60 - $8,288.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Biological Sciences', 'Chemistry', 'Computer Science', 'Earth Sciences', 'Environmental Science', 'Geography', 'Mathematics', 'Physics', 'Psychology', 'Statistics'],
      prerequisites: 'NCEA Level 3 with University Entrance; Mathematics and Sciences recommended for certain majors',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Sport, Health and Physical Education',
      cost: 'NZD $7,185.60 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in physical education or sciences beneficial',
    },
    {
      uni: 'University of Auckland',
      name: 'Bachelor of Urban Planning (Honours)',
      cost: 'NZD $8,288.40 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'NCEA Level 3 with University Entrance; background in geography or social sciences recommended',
    },

    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Architecture and Future Environments',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; portfolio submission may be required',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Arts',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Criminology', 'Event Management', 'International Studies', 'Japanese', 'Psychology', 'Social Sciences', 'Te Reo Māori'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Business',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Accounting', 'Economics', 'Finance', 'Human Resource Management and Employment Relations', 'Information Systems', 'International Business', 'Management', 'Marketing', 'Sustainable Enterprise'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Communication Studies',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Advertising Creativity', 'Digital Media', 'Journalism', 'Public Relations', 'Radio and Audio Media', 'Screen Production'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Computer and Information Sciences',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Analytics', 'Artificial Intelligence', 'Cybersecurity', 'Networks and Cybersecurity', 'Software Development'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Construction',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Design',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Communication Design', 'Fashion Design', 'Industrial Design', 'Interaction Design', 'Spatial Design'],
      prerequisites: 'University Entrance; portfolio submission may be required',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Education (Teaching)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in education or related subjects beneficial',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Engineering (Honours)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Architectural Engineering', 'Electrical and Electronic Engineering', 'Mechanical Engineering', 'Mechatronics Engineering', 'Software Engineering'],
      prerequisites: 'University Entrance; strong performance in Mathematics with Calculus and Physics required',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Engineering Technology',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Electrical Engineering', 'Mechanical Engineering', 'Network and Communication Engineering'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Health Science',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North and South Campuses, Auckland',
      minors: ['Case Management', 'Health Promotion', 'Management', 'Psychology', 'Public and Environmental Health'],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Health Science (Midwifery)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Health Science (Nursing)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North and South Campuses, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Health Science (Occupational Therapy)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Health Science (Oral Health)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Health Science (Physiotherapy)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Health Science (Podiatry)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of International Hospitality Management',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Event Management', 'Hospitality Enterprise', 'Tourism'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Laws',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; high academic achievement required',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Medical Laboratory Science',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; background in sciences required',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Science',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: ['Analytics', 'Astronomy and Space Science', 'Bioanalytical Chemistry', 'Biochemistry', 'Biodiversity Conservation', 'Biomedical Science', 'Chemical Science', 'Earth System Science', 'Environmental Science', 'Environmental Sustainability', 'Food Science', 'Geospatial Science', 'Marine Science', 'Mathematical Modelling and Computation', 'Microbiology', 'Molecular Genetics', 'Pharmaceutical Formulation'],
      prerequisites: 'University Entrance; Mathematics and Sciences recommended',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Sport, Exercise and Health',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'North Campus, Auckland',
      minors: ['Exercise Science and Nutrition', 'Health and Physical Education', 'Management', 'Recreation and Sports Management'],
      prerequisites: 'University Entrance; background in physical education or sciences beneficial',
    },
    {
      uni: 'Auckland University of Technology',
      name: 'Bachelor of Visual Arts',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'City Campus, Auckland',
      minors: [],
      prerequisites: 'University Entrance; portfolio submission may be required',
    },

    {
      uni: 'University of Waikato',
      name: 'Bachelor of Applied Computing',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: ['Computer Science', 'Data Analytics', 'Mathematics', 'Applied Computing'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Arts',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: ['Anthropology', 'Chinese', 'English', 'French', 'Geography', 'History', 'Japanese', 'Linguistics', 'Māori and Indigenous Studies', 'Pacific and Indigenous Studies', 'Philosophy', 'Political Science', 'Psychology', 'Sociology', 'Spanish', 'Te Reo Māori'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Banking, Finance and Technology',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Finance', 'Information Systems', 'Economics', 'Data Analytics'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Business',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: ['Accounting', 'Economics', 'Finance', 'Human Resource Management', 'Marketing', 'Public Relations', 'Strategic Management', 'Supply Chain Management'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Climate Change',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Environmental Planning', 'Geography', 'Public Policy', 'Sustainability'],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Communication',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: ['Digital Media', 'Journalism', 'Marketing', 'Public Relations', 'Screen and Media Studies'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Computer Graphic Design',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Communication Design', 'Interaction Design', 'Media Design'],
      prerequisites: 'University Entrance; portfolio submission may be required',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Computer Science',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Artificial Intelligence', 'Cyber Security', 'Data Analytics', 'Software Engineering'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Design',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Communication Design', 'Industrial Design', 'Interaction Design', 'Spatial Design'],
      prerequisites: 'University Entrance; portfolio submission may be required',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Education',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: ['Early Childhood Education', 'Primary Education', 'Secondary Education'],
      prerequisites: 'University Entrance; background in education or related subjects beneficial',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Engineering',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Chemical and Biological Engineering', 'Civil Engineering', 'Electrical and Electronic Engineering', 'Mechanical Engineering', 'Software Engineering'],
      prerequisites: 'University Entrance; strong performance in Mathematics with Calculus and Physics required',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Environmental Planning',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Environmental Science', 'Geography', 'Public Policy', 'Sustainability'],
      prerequisites: 'University Entrance; background in geography or environmental studies recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Global Studies',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['International Relations', 'Languages', 'Political Science', 'Sociology'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Health',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Community Health', 'Health Promotion', 'Public Health', 'Psychology'],
      prerequisites: 'University Entrance; background in sciences recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Laws',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: ['Commercial Law', 'Criminal Law', 'Environmental Law', 'Human Rights Law'],
      prerequisites: 'University Entrance; high academic achievement required',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Management Studies',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Accounting', 'Economics', 'Finance', 'Human Resource Management', 'Marketing', 'Public Relations', 'Strategic Management', 'Supply Chain Management'],
      prerequisites: 'University Entrance; Mathematics recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Media and Creative Technologies',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Creative Media', 'Digital Media', 'Screen and Media Studies', 'Theatre Studies'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Music',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Composition', 'Musicology', 'Performance', 'Popular Music'],
      prerequisites: 'University Entrance; audition may be required',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Nursing',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: [],
      prerequisites: 'University Entrance; background in sciences required',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Science',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Biochemistry', 'Biological Sciences', 'Chemistry', 'Computer Science', 'Earth Sciences', 'Ecology and Biodiversity', 'Electronics', 'Environmental Sciences', 'Mathematics', 'Physics', 'Psychology'],
      prerequisites: 'University Entrance; Mathematics and Sciences recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Science (Technology)',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: ['Biochemistry', 'Biological Sciences', 'Chemistry', 'Computer Science', 'Earth Sciences', 'Ecology and Biodiversity', 'Electronics', 'Environmental Sciences', 'Mathematics', 'Physics', 'Psychology'],
      prerequisites: 'University Entrance; Mathematics and Sciences recommended',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Social Sciences',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: ['Anthropology', 'Economics', 'Education and Society', 'Geography', 'Human Development', 'Political Science', 'Psychology', 'Public Policy', 'Sociology'],
      prerequisites: 'University Entrance',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Social Work',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton campus',
      minors: [],
      prerequisites: 'University Entrance; background in social sciences beneficial',
    },
    {
      uni: 'University of Waikato',
      name: 'Bachelor of Sport and Human Performance',
      cost: 'Approximately NZD $7,000–$8,000 per year for domestic students',
      location: 'Hamilton and Tauranga campuses',
      minors: [],
      prerequisites: 'University Entrance',
    },

    {
      uni: 'Massey University',
      name: 'Bachelor of Accountancy',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland, Manawatū (Palmerston North), and online',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Agribusiness',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Agricultural Science',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Animal Science',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Arts',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland, Manawatū (Palmerston North), Wellington, and online',
      minors: ['Anthropology', 'Chinese', 'Classical Studies', 'Creative Writing', 'Defence Studies', 'Development Studies', 'Disability and Rehabilitation Studies', 'Economics', 'Education', 'Educational Psychology', 'Emergency Management', 'English', 'Environmental Studies', 'French', 'Geography', 'History', 'Indigenous Psychologies', 'Japanese', 'Linguistics', 'Māori Knowledge', 'Mathematics', 'Media Studies', 'Philosophy', 'Politics and International Relations', 'Psychology', 'Security Studies', 'Social Anthropology', 'Sociology', 'Spanish', 'Statistics', 'Te Reo Māori', 'Theatre Studies'],
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Aviation',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; pilot aptitude assessment; Class 1 Medical Certificate',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Aviation Management',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North) and online',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Business',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland, Manawatū (Palmerston North), Wellington, and online',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Commercial Music',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Wellington',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; audition may be required',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Communication',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland, Wellington, and online',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Construction',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; background in mathematics recommended',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Design',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Wellington',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; portfolio submission may be required',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Earth and Environmental Science',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; background in science subjects recommended',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Fine Arts',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Wellington',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; portfolio submission may be required',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Health Science',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland, Manawatū (Palmerston North), Wellington, and online',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification; background in science subjects recommended',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Horticultural Science',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; background in biology or agriculture beneficial',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Information Sciences',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland and online',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification; background in mathematics recommended',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Māori Visual Arts',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; portfolio submission may be required',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Nursing',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland and Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; background in science subjects recommended; may require interview and health checks',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Resource and Environmental Planning',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Science',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland, Manawatū (Palmerston North), and online',
      minors: 'Available from recognized undergraduate degrees',
      prerequisites: 'University Entrance qualification; background in science subjects recommended',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Screen Arts',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Wellington',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; portfolio submission may be required',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Social Work',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Auckland, Manawatū (Palmerston North), and online',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; may require interview and background checks',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Sport and Exercise',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; background in physical education or science subjects recommended',
    },
    {
      uni: 'Massey University',
      name: 'Bachelor of Veterinary Science',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification; competitive entry; background in science subjects required',
    },
    {
      uni: 'Massey University',
      name: 'Te Aho Tātairangi: Bachelor of Teaching and Learning Kura Kaupapa Māori',
      cost: "Refer to Massey University's tuition fees page",
      location: 'Manawatū (Palmerston North)',
      minors: 'Not specified',
      prerequisites: 'University Entrance qualification',
    },

    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Arts (BA)',
      cost: 'NZD $7,348 per 120 points',
      location: 'Ilam Campus, Christchurch',
      minors: ['Accounting', 'Anthropology', 'Art History and Theory', 'Chinese', 'Classics', 'Cultural Studies', 'Economics', 'Education', 'English', 'European and European Union Studies', 'Film', 'French', 'Gender Studies', 'Geography', 'German', 'History', 'Human Services', 'Japanese', 'Linguistics', 'Maori and Indigenous Studies', 'Mathematics', 'Media and Communication', 'Music', 'Philosophy', 'Political Science and International Relations', 'Psychology', 'Russian', 'Sociology', 'Spanish', 'Te Reo Maori'],
      prerequisites: 'University Entrance qualification; specific majors may have additional requirements.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Commerce (BCom)',
      cost: 'NZD $7,503 per 120 points',
      location: 'Ilam Campus, Christchurch',
      minors: ['Accounting', 'Economics', 'Finance', 'Human Resource Management', 'Information Systems', 'International Business', 'Management', 'Marketing', 'Operations and Supply Chain Management', 'Strategy and Entrepreneurship'],
      prerequisites: 'University Entrance qualification; specific majors may have additional requirements.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Communication (BC)',
      cost: 'NZD $7,348 per 120 points',
      location: 'Ilam Campus, Christchurch',
      minors: ['Intercultural Communication', 'Literary and Creative Communication', 'Marketing Communication', 'Political Communication'],
      prerequisites: 'University Entrance qualification; specific minors may have additional requirements.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Criminal Justice (BCJ)',
      cost: 'NZD $7,348 per 120 points',
      location: 'Ilam Campus, Christchurch',
      minors: ['Criminology', 'Psychology', 'Sociology'],
      prerequisites: 'University Entrance qualification; specific minors may have additional requirements.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Data Science (BDataSc)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Computer Science', 'Mathematics', 'Statistics'],
      prerequisites: 'University Entrance qualification; strong background in mathematics recommended.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Digital Screen with Honours (BDigitalScreen(Hons))',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Film', 'Media and Communication'],
      prerequisites: 'University Entrance qualification; portfolio submission may be required.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Engineering with Honours (BE(Hons))',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Civil Engineering', 'Electrical and Electronic Engineering', 'Mechanical Engineering', 'Mechatronics Engineering', 'Software Engineering'],
      prerequisites: 'University Entrance qualification with strong performance in mathematics and physics.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Environmental Science with Honours (BEnvSci(Hons))',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Geography', 'Geology', 'Biology'],
      prerequisites: 'University Entrance qualification; background in science subjects recommended.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Fine Arts (BFA)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Painting', 'Photography', 'Printmaking', 'Sculpture'],
      prerequisites: 'University Entrance qualification; portfolio submission required.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Forestry Science (BForSc)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Forest Management', 'Forest Engineering'],
      prerequisites: 'University Entrance qualification; background in science subjects recommended.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Health Sciences (BHSc)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Health Education', 'Public Health', 'Psychology', 'Sociology'],
      prerequisites: 'University Entrance qualification; background in science subjects recommended.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Laws (LLB)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Not applicable'],
      prerequisites: 'University Entrance qualification; specific entry requirements apply.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Māori Innovation (BMāoriInno)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Māori and Indigenous Studies', 'Business', 'Design'],
      prerequisites: 'University Entrance qualification; background in Māori culture recommended.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Music (BMus)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Composition', 'Performance', 'Music Technology'],
      prerequisites: 'University Entrance qualification; audition required.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Product Design (BProdDesign)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Design', 'Engineering', 'Business'],
      prerequisites: 'University Entrance qualification; portfolio submission required.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Psychological Science (BPsychSc)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Psychology'],
      prerequisites: 'University Entrance qualification; background in science subjects recommended.',
    },
    {
      uni: 'University of Canterbury',
      name: 'Bachelor of Science (BSc)',
      cost: 'NZD $7,348 per 120 points',

      location: 'Ilam Campus, Christchurch',
      minors: ['Astronomy', 'Biochemistry', 'Biological Sciences', 'Chemistry', 'Computer Science', 'Data Science', 'Ecology', 'Environmental Science', 'Geology', 'Mathematics', 'Physics', 'Psychology', 'Statistics'],
      prerequisites: 'University Entrance qualification; specific majors may have additional requirements.',
    },

    {
      uni: 'Lincoln University',
      name: 'Bachelor of Agribusiness and Food Marketing',
      cost: 'NZD $7,178 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Agribusiness', 'Food Marketing'],
      prerequisites: 'University Entrance qualification; recommended background in Business Studies, Economics, and Mathematics.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Agricultural Science',
      cost: 'NZD $8,200 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Agronomy', 'Animal Science', 'Soil Science'],
      prerequisites: 'University Entrance qualification; strong background in Biology, Chemistry, and Mathematics recommended.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Agriculture',
      cost: 'NZD $8,165 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Farm Management', 'Agronomy', 'Animal Science'],
      prerequisites: 'University Entrance qualification; recommended background in Agriculture, Biology, and Mathematics.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Commerce',
      cost: 'NZD $6,810 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Accounting', 'Finance', 'Marketing', 'Economics', 'Management'],
      prerequisites: 'University Entrance qualification; recommended background in Business Studies, Economics, and Mathematics.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Environmental Policy and Planning (Honours)',
      cost: 'NZD $7,519 per 120 credits (years 1–3), NZD $8,854 per 120 credits (year 4)',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Environmental Policy', 'Urban Planning', 'Sustainable Development'],
      prerequisites: 'University Entrance qualification; recommended background in Geography, Social Studies, and Environmental Science.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Environmental Management',
      cost: 'NZD $7,532 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Environmental Science', 'Sustainability', 'Resource Management'],
      prerequisites: 'University Entrance qualification; recommended background in Environmental Science, Geography, and Biology.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Science',
      cost: 'NZD $8,045 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Biology', 'Chemistry', 'Physics', 'Mathematics', 'Computer Science'],
      prerequisites: 'University Entrance qualification; strong background in Science subjects recommended.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Sport and Recreation Management',
      cost: 'NZD $6,967 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Sport Management', 'Recreation Planning', 'Event Management'],
      prerequisites: 'University Entrance qualification; recommended background in Physical Education, Sports Studies, and Management.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Tourism Management',
      cost: 'NZD $6,767 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Tourism Planning', 'Event Management', 'Sustainable Tourism'],
      prerequisites: 'University Entrance qualification; recommended background in Geography, Social Studies, and Business Studies.',
    },
    {
      uni: 'Lincoln University',
      name: 'Bachelor of Viticulture and Oenology',
      cost: 'NZD $8,242 per 120 credits',

      location: 'Lincoln, Canterbury, New Zealand',
      minors: ['Viticulture', 'Oenology', 'Wine Business'],
      prerequisites: 'University Entrance qualification; recommended background in Biology, Chemistry, and Agriculture.',
    },

    {
      uni: 'University of Otago',
      name: 'Bachelor of Arts (BA)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Anthropology', 'Archaeology', 'Art History', 'Chinese', 'Classics', 'Criminology', 'Education', 'English', 'Film and Media Studies', 'French', 'Gender Studies', 'Geography', 'German', 'History', 'Indigenous Studies', 'Italian', 'Japanese', 'Linguistics', 'Maori Studies', 'Philosophy', 'Political Studies', 'Psychology', 'Sociology', 'Spanish', 'Theology'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Arts and Commerce (BACom)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Anthropology', 'Art History', 'Chinese', 'Classics', 'Criminology', 'Education', 'English', 'Film and Media Studies', 'French', 'Gender Studies', 'Geography', 'German', 'History', 'Indigenous Studies', 'Italian', 'Japanese', 'Linguistics', 'Maori Studies', 'Philosophy', 'Political Studies', 'Psychology', 'Sociology', 'Spanish', 'Theology'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Arts and Science (BASc)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Anthropology', 'Archaeology', 'Art History', 'Chinese', 'Classics', 'Criminology', 'Education', 'English', 'Film and Media Studies', 'French', 'Gender Studies', 'Geography', 'German', 'History', 'Indigenous Studies', 'Italian', 'Japanese', 'Linguistics', 'Maori Studies', 'Philosophy', 'Political Studies', 'Psychology', 'Sociology', 'Spanish', 'Theology'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Biomedical Sciences (BBioMedSc)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Anatomy', 'Biochemistry', 'Biotechnology', 'Chemistry', 'Genetics', 'Microbiology', 'Neuroscience', 'Pharmacology', 'Physiology', 'Zoology'],
      prerequisites: 'University Entrance qualification; strong background in Biology and Chemistry recommended.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Commerce (BCom)',
      cost: 'NZD $6,625 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Accounting', 'Economics', 'Finance', 'Information Science', 'International Business', 'Management', 'Marketing', 'Public Policy', 'Tourism'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Commerce and Science (BComSc)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Accounting', 'Biochemistry', 'Biology', 'Chemistry', 'Computer Science', 'Economics', 'Finance', 'Geography', 'Information Science', 'Management', 'Marketing', 'Mathematics', 'Physics', 'Statistics', 'Zoology'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Design (BDes)',
      cost: 'NZD $8,291 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Communication Design', 'Digital Design', 'Fashion Design', 'Industrial Design', 'Interior Architecture', 'Product Design'],
      prerequisites: 'University Entrance qualification; portfolio submission required.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Education (BEd)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Early Childhood Education', 'Primary Education', 'Secondary Education'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Fine Arts (BFA)',
      cost: 'NZD $8,291 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Ceramics', 'Drawing', 'Painting', 'Photography', 'Printmaking', 'Sculpture'],
      prerequisites: 'University Entrance qualification; portfolio submission required.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Health Sciences (BHealSc)',
      cost: 'NZD $9,584 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Anatomy', 'Biochemistry', 'Biotechnology', 'Chemistry', 'Genetics', 'Microbiology', 'Neuroscience', 'Pharmacology', 'Physiology', 'Zoology'],
      prerequisites: 'University Entrance qualification; strong background in Biology and Chemistry recommended.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Laws (LLB)',
      cost: 'NZD $7,740 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Criminal Law', 'Environmental Law', 'International Law', 'Public Law'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Music (MusB)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Composition', 'Musicology', 'Performance', 'Technology'],
      prerequisites: 'University Entrance qualification; audition required.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Performing Arts (BPA)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Dance', 'Drama', 'Music', 'Theatre Studies'],
      prerequisites: 'University Entrance qualification; audition required.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Science (BSc)',
      cost: 'NZD $6,938 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Anatomy', 'Biochemistry', 'Biology', 'Chemistry', 'Computer Science', 'Geography', 'Geology', 'Mathematics', 'Physics', 'Psychology', 'Statistics', 'Zoology'],
      prerequisites: 'University Entrance qualification; specific subjects may have additional requirements.',
    },
    {
      uni: 'University of Otago',
      name: 'Bachelor of Surveying (BSurv)',
      cost: 'NZD $9,584 per 120 credits',

      location: 'Dunedin, New Zealand',
      minors: ['Land Surveying', 'Geomatics', 'Land Development'],
      prerequisites: 'University Entrance qualification; strong background in Mathematics and Physics recommended.',
    },

    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Arts (BA)',
      cost: 'NZD $6,543.60/year (domestic)',
      prerequisites: 'NCEA Level 3 or equivalent; specific course requirements vary by degree',
      minors: ['Anthropology', 'Criminology', 'Education', 'Geography', 'History', 'International Relations', 'Philosophy', 'Political Science', 'Psychology', 'Sociology'],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Science (BSc)',
      cost: 'NZD $7,195.20/year (domestic)',
      prerequisites: 'NCEA Level 3 with science subjects preferred',
      minors: ['Actuarial Science', 'Artificial Intelligence', 'Biology', 'Chemistry', 'Computer Science', 'Data Science', 'Earth Sciences', 'Environmental Studies', 'Geography', 'Mathematics', 'Physics', 'Psychology', 'Statistics'],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Commerce (BCom)',
      cost: 'NZD $7,699.20/year (domestic)',
      prerequisites: 'NCEA Level 3 including numeracy and literacy requirements',
      minors: ['Accounting', 'Economics', 'Finance', 'Human Resource Management', 'International Business', 'Information Systems', 'Management', 'Marketing', 'Public Policy', 'Taxation'],
      location: 'Pipitea Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Architectural Studies (BAS)',
      cost: 'NZD $9,099.60/year (domestic)',
      prerequisites: 'NCEA Level 3 including approved subjects; portfolio or interview may be required',
      minors: [],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Design (BDes)',
      cost: 'NZD $8,178.00/year (domestic)',
      prerequisites: 'NCEA Level 3 or equivalent; portfolio may be required',
      minors: [],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Engineering with Honours (BE(Hons))',
      cost: 'NZD $9,580.80/year (domestic)',
      prerequisites: 'NCEA Level 3 with specific subjects; refer to course finder for details',
      minors: [],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Health (BHlth)',
      cost: 'NZD $7,699.20/year (domestic)',
      prerequisites: 'NCEA Level 3 with specific subjects; refer to course finder for details',
      minors: ['Health Informatics', 'Health Promotion', 'Health Psychology', 'Health Software Development', 'Public Health'],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Communication (BC)',
      cost: 'NZD $7,699.20/year (domestic)',
      prerequisites: 'NCEA Level 3 or equivalent; specific course requirements vary by major',
      minors: ['Intercultural Communication', 'Journalism', 'Public Relations', 'Media Studies'],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Music (BMus)',
      cost: 'NZD $8,178.00/year (domestic)',
      prerequisites: 'NCEA Level 3 with music subjects; audition may be required',
      minors: [],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Biomedical Science (BBiomedSc)',
      cost: 'NZD $7,195.20/year (domestic)',
      prerequisites: 'NCEA Level 3 with specific science subjects',
      minors: ['Biochemistry', 'Biotechnology', 'Cell and Molecular Bioscience', 'Genetics', 'Immunology', 'Microbiology', 'Pharmacology'],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Construction (BConst)',
      cost: 'NZD $7,699.20/year (domestic)',
      prerequisites: 'NCEA Level 3 with specific subjects; refer to course finder for details',
      minors: ['Building Surveying', 'Built and Natural Heritage Conservation', 'Construction Health and Safety', 'Construction Management', 'Project Management', 'Smart Cities and Digital Built Environments', 'Sustainable Construction'],
      location: 'Te Aro Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Environment and Society (BEnvS)',
      cost: 'NZD $6,543.60/year (domestic)',
      prerequisites: 'NCEA Level 3 or equivalent; specific course requirements vary by major',
      minors: ['Environmental Policy', 'Sustainable Development', 'Urban Studies'],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Philosophy, Politics and Economics (PPE)',
      cost: 'NZD $6,543.60/year (domestic)',
      prerequisites: 'NCEA Level 3 or equivalent; specific course requirements vary by major',
      minors: [],
      location: 'Kelburn Campus',
    },
    {
      uni: 'Victoria University of Wellington',
      name: 'Bachelor of Psychology (BPsych)',
      cost: 'NZD $7,195.20/year (domestic)',
      prerequisites: 'NCEA Level 3 with specific subjects; refer to course finder for details',
      minors: ['Psychological Science'],
      location: 'Kelburn Campus',
    },
  ]

  // let content = getplans()
  // let contents = [
  //   {
  //     uni: '',
  //     cost: '',
  //     prerequisits: '',
  //     name: '',
  //   },
  //   {
  //     uni: '',
  //     cost: '',
  //     prerequisits: '',
  //     name: '',
  //   },
  //   {
  //     uni: '',
  //     cost: '',
  //     prerequisits: '',
  //     name: '',
  //   },
  // ]
</script>

<Header />

<nav>
  <a href="/searchpage">searchpage</a>
  <a href="/loginpage">loginpage</a>
  <a href="/">home</a>
</nav>
<input type="text" placeholder="Search.." name="search" />
<button type="submit"><img src="loupe.png" alt="" /></button>
<!-- {#await content}
  <p>Loading...</p>
{:then content} -->
<table>
  <thead>
    <tr>
      <th>course</th>
      <th>University</th>
      <th>cost</th>
      <th>prerequisites</th>
    </tr>
  </thead>
  <tbody>
    {#each content as course}
      <tr>
        <td>{course.name}</td>
        <td>{course.uni}</td>
        <td>{course.cost}</td>
        <td>{course.prerequisites}</td>
      </tr>
    {/each}
  </tbody>
</table>
<!-- {/await} -->
<Footer />

<style>
  img {
    width: 15px;
  }
  table,
  tr,
  td,
  th {
    border: 1px solid black;
    padding: 5px;
  }
  table {
    margin: 20px;
  }
</style>
